spring:
  application:
    name: df-sso-service
  datasource:
    name:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
#sso
SESSION_EXPIRE: 604800
USER_INFO: USER_INFO
